### Welcome to Jekyll Webpack Boilerplate
#
# This config file contains the config of your webpages
# You may also want to update /config/webpack.pwa.js in case you want to generate a Progressive Web App

title: Smart Currency
email: info@llama.vn
description: 'Currency: Smart converter'
url: "http://apps.llama.vn/currency" # the base hostname & protocol for your site, e.g. http://example.com
theme_color: '#efeeff'
logo: ./assets/images/logo.png
languages: ["en"]

github: https://github.com/llamavn/currency-landing

### Google webmaster tools, Google Analytics and Cookie consent uncomment and put the API key
#webmaster_verifications:
#  google: verification_code
#google_analytics: UA-XXXXXXXXX-X
#cookie_consent: true

### Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - octopress-minify-html

### Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - _images
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.png
  - logo.png

collections:
  pages:
    output: true
    permalink: /:path/