name: CURRENCY
description: 'Currency: Smart converter'
full_description: >
  Smart Currency Converter helps you effortlessly convert currencies with real-time rates.<br><br>

  With a lot of features:<br>
  - Real-time exchange rates for global currencies.
  - Quick and easy conversion.
  - Dark mode for nighttime use.
  - Copy results instantly.
  - View and track conversion history.
iOS: https://apps.apple.com/app/currency-smart-converter/id6738375801
screenshots:
  - 1.png
  - 2.png
  - 3.png
  - 4.png
  - 5.png
