name: CURRENCY
description: 'Currency: Smart converter'
full_description: >
  Smart Currency Converter helps you effortlessly convert currencies with real-time rates.<br><br>

  With a lot of features:<br>
    - Real-time exchange rates for global currencies.<br>
    - Quick and easy conversion.<br>
    - Dark mode for nighttime use.<br>
    - Copy results instantly.<br>
    - View and track conversion history.<br>
iOS: https://apps.apple.com/app/currency-smart-converter/id6738375801
screenshots:
  - 1.png
  - 2.png
  - 3.png
  - 4.png
  - 5.png
